### ISSUE TITLE
Broken filter creation

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#114]
Ran into a few more bumps trying out the new trend page.

First: I _really_ dig the new option to filter on `sample_data` fields, that is quite handy. It has the same display issue as field selection on the main trend page though: ugly field names and only lists the first 30. New problem specific to filter is that the comparison operators are only numeric. We definitely need string operators and date/range operators there. 

![filter_sample](https://user-images.githubusercontent.com/5105646/75244463-20980500-57cc-11ea-9c62-15086e42c8ef.png)

Filtering on `report_metadata` is also broken. The `key` options are just ints (`report_metadata_id` maybe?), listing only the first 30, and the same limited operators as the `sample_data` selection.

![filter_metadata](https://user-images.githubusercontent.com/5105646/75244485-27bf1300-57cc-11ea-8c95-e03df0aa176e.png)

The `specific_dates` and `dynamic_date_range` options: neither allow the selecting of the field to be used, and choosing `specific_dates` hangs the page until it is killed.

![filter_range](https://user-images.githubusercontent.com/5105646/75244502-2db4f400-57cc-11ea-9e02-1c7d28099940.png)

![Screenshot from 2020-02-25 12-42-11](https://user-images.githubusercontent.com/5105646/75244577-4d4c1c80-57cc-11ea-9095-a7e53f008a2a.png)

**Comment by TMiguelT** [comment]
Okay, I'm working on a fix for this now. I've also added an edit button to the filter selection since it was sorely needed here: 
![image](https://user-images.githubusercontent.com/5019367/87021508-aadf8380-c218-11ea-8d44-96dcd0052a80.png)

I'll aim to fix the above issues next. I'll be tracking it here: https://github.com/ewels/MegaQC/pull/121.

**Comment by TMiguelT** [comment]
> New problem specific to filter is that the comparison operators are only numeric. We definitely need string operators and date/range operators there

Did this ever work? Because I'm looking at the original filter code and I can't find any string subset filters like the SQL `IN` operator.

**Comment by tsnowlan** [comment]
Yeah, one of the most useful filters we made was looking at values from the past 90 days whose sample IDs matched patterns for different units (cancer, exome, genome, etc). I'm not sure where in the codebase the functionality was, but it worked.

**Comment by TMiguelT** [comment]
Thanks, actual use-cases are invaluable when I'm working on features like this. 

Quick questions:

* Which field were you using as the "sample ID"? Was it a report metadata item, or a sample data item?
* Were you using SQL `LIKE` patterns e.g. `%1234%`? I could implement regex but that seems like a lot of effort since SQLAlchemy doesn't support them natively
* Do you think `column (contains|like) user_input` are sufficient options? Any others you might want? Is there any merit to a `contained_by` operator? (I can't think of any)"

**Comment by tsnowlan** [comment]
* It was a report metadata field, `report_config_title` or something similar
* There were no SQL operators visible to the user, I believe the options were "starts with", "ends with" and "contains". I don't think implementing regex is really necessary for this, but maybe @ewels thinks otherwise?
* Contains / starts with / ends with (`%str%`, `str%`, `%str`) are probably sufficient for most use cases

**Comment by ewels** [comment]
Agreed 👍 Keep it simple until forced to do otherwise..

**Comment by TMiguelT** [comment]
Fixed in #121.
