### ISSUE TITLE
No error message when plotting non-numeric field type

### ISSUE THREAD

**Issue by tsnowlan** [ewels/MegaQC#116]
When a field is selected that is not a numeric type, the rest API throws a 500 but there's no notification to the user on why a plot isn't generated. This was an issue in the old version as well, though in that case there wasn't even a 500 in the logs.

Would be better to have a little toast banner with an error message or filter out fields that can't be used before they get to the UI?

**Comment by TMiguelT** [comment]
Yes, I feel that something is needed to indicate that it's not going to work. The trouble is, if we make a toast each time, scrolling through the data types is going to absolutely inundate the UI with failures (since there might be 20 data types in a row that aren't numeric). Eventually I hope to add a JSON schema to each data type, and we'll be able to filter out non-numeric data types from the trend plot selection box, but for now I'll try to think of a subtle UI indication that it failed.
