### ISSUE TITLE
DB initializing only checks whether environment variable is set, but not whether it is 1 or 0

### ISSUE THREAD

**Issue by Zethson** [ewels/MegaQC#170]
**Describe the bug**

When messing around with the setup I set the FLASK_DEBUG env to 0. 
However, MegaQC expects it to be unset. 

**Expected behavior**

I expect MegaQC to treat those special ENVs as unset if equal to 0.

**Comment by TMiguelT** [comment]
It's true that this is a little unintuitive. It's not a particularly simple fix because even `FLASK_DEBUG=0` is actually setting the variable to the string `"0"` which is a truthy value in Python. A more stable solution might be to use something like this library: https://pypi.org/project/env-flag/.
